---
identifier: system_design_spending_tracker
name: "Spending Tracker"
category: system_design
difficulty: medium
description:
  en: README_en.md
solution:
  en: SOLUTION_en.md
industries:
  - finance
