---
identifier: coding_alien_dictionary
name: "Alien Dictionary"
category: coding
subcategory: "graph"
difficulty: hard
description:
  en: README_en.md
solution:
  en: SOLUTION_en.md
starter_code:
  c: "starter.c"
  cpp: "starter.cpp"
  go: "starter.go"
  javascript: "starter.js"
  python: "starter.py"
  ruby: "starter.rb"
  java: "starter.java"
industries:
  - education
