---
identifier: coding_course_schedule
name: "Course Schedule"
category: coding
subcategory: "graph"
description:
  en: README_en.md
solution:
  en: SOLUTION_en.md
starter_code:
  c: "starter.c"
  cpp: "starter.cpp"
  go: "starter.go"
  javascript: "starter.js"
  python: "starter.py"
  ruby: "starter.rb"
industries:
  - education
difficulty: medium
