---
identifier: system_design_photo_sharing
name: "Photo Sharing"
category: system_design
difficulty: medium
description:
  en: README_en.md
solution:
  en: SOLUTION_en.md
industries:
  - finance
  - education
  - ecommerce
  - social_media
  - dev_tools
