---
identifier: coding_find_median_from_data_stream
category: coding
subcategory: "Design"
difficulty: hard
description:
  en: README_en.md
solution:
  en: SOLUTION_en.md
starter_code:
  c: "starter.c"
  cpp: "starter.cpp"
  go: "starter.go"
  javascript: "starter.js"
  python: "starter.py"
  ruby: "starter.rb"
industries:
