---
identifier: coding_longest_increasing_subsequence
name: "Longest Increasing Subsequence"
category: coding
subcategory: "dynamic_programming"
difficulty: medium
description:
  en: README_en.md
solution:
  en: SOLUTION_en.md
starter_code:
  c: "starter.c"
  cpp: "starter.cpp"
  go: "starter.go"
  javascript: "starter.js"
  python: "starter.py"
  ruby: "starter.rb"
  java: "starter.java"
industries:
