name: Test Coding JSON

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: DRY_RUN rake generate_coding_json
        id: generate-coding-json
        run: |
          DRY_RUN=true rake generate_coding_json
      - name: Echo new version
        env:
          JSON_VERSION: ${{steps.generate-coding-json.outputs.CODING_JSON_VERSION}}
        run: |
          echo "New Coding JSON version: $JSON_VERSION"
